============================= test session starts =============================
platform win32 -- Python 3.6.12, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: D:\pythonproject\ProgramData\AutoTestProject\hello, configfile: pytest.ini
plugins: dependency-0.5.1, forked-1.3.0, html-2.1.1, metadata-1.10.0, ordering-0.6, rerunfailures-9.1.1, xdist-2.2.0
collected 3 items

test_fail.py test_one
.test_two
FÖ´ÐÐmyfixture
test_three
.

================================== FAILURES ===================================
____________________________ Test_Pytest.test_two _____________________________

self = <test_fail.Test_Pytest object at 0x00000000044F5240>

    def test_two(self):
        print("test_two")
>       assert "s" in "love"
E       AssertionError: assert 's' in 'love'

test_fail.py:20: AssertionError
- generated html file: file://D:\pythonproject\ProgramData\AutoTestProject\hello\test_fail\report.html -
=========================== short test summary info ===========================
FAILED test_fail.py::Test_Pytest::test_two - AssertionError: assert 's' in 'l...
========================= 1 failed, 2 passed in 0.34s =========================
============================= test session starts =============================
platform win32 -- Python 3.6.12, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: D:\pythonproject\ProgramData\AutoTestProject\hello, configfile: pytest.ini
plugins: dependency-0.5.1, forked-1.3.0, html-2.1.1, metadata-1.10.0, ordering-0.6, rerunfailures-9.1.1, xdist-2.2.0
collected 3 items / 2 deselected / 1 selected
run-last-failure: rerun previous 1 failure

test_fail.py test_two
F

================================== FAILURES ===================================
____________________________ Test_Pytest.test_two _____________________________

self = <test_fail.Test_Pytest object at 0x00000000044D12B0>

    def test_two(self):
        print("test_two")
>       assert "s" in "love"
E       AssertionError: assert 's' in 'love'

test_fail.py:20: AssertionError
- generated html file: file://D:\pythonproject\ProgramData\AutoTestProject\hello\test_fail\report2.html -
=========================== short test summary info ===========================
FAILED test_fail.py::Test_Pytest::test_two - AssertionError: assert 's' in 'l...
======================= 1 failed, 2 deselected in 0.39s =======================
